#include "./lexer.h"

#include <stdio.h>
#include <assert.h>

/*********************************
 * variable and function from flex
 * *******************************/
// lexer input handler
extern FILE *c_wc_in;
// main lexer function generated by flex
extern int c_wc_lex(Lexer *lex);

Lexer::Lexer(const char *fname)
{
   c_wc_in = fopen(fname, "r");
   assert(c_wc_in != nullptr);
}

Lexer::~Lexer()
{
   fclose(c_wc_in);
}

void Lexer::count()
{
   c_wc_lex(this);
   dump();
}

void Lexer::dump() const
{
   printf("The statistics of the source code:\n");
   printf("\tCode line number: %d, comment line number: %d, empty line number: %d\n",
      m_codeLineNum, m_commentLineNum, m_emptyLineNum);
   printf("\tIf number: %d, loop number: %d\n", m_ifNum, m_loopNum);
}
